---
title: "Lista de exercicios 1"
author: "Rafael Izbicki e Rafael Bassi Stern"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
output: html_document
bibliography: ipaee.bib
---

1. [@Wickham2016] Para este exercício, carregue
o banco de dados "diamonds" do pacote "tidyverse":

```
library(tidyverse)
data(diamonds)
```

Um dicionário para este banco de dados
pode ser obtido por meio do comando:

```
help(diamonds)
```

- Classifique as variáveis "carat", "cut",
"color", "clarity" e "price" quanto ao seu tipo.

- Utilize medidas resumo e gráficos adequados para 
descrever cada uma das variáveis acima.
Interprete os resultados.

- Qual variável no banco de dados está
mais associada ao preço de um diamante?

- Use boxplots para investigar a associação entre
o preço de um diamante e a qualidade do seu corte.
Utilize o item acima para explicar este resultado.

2. [@Wickham2016] Para este exercício, carregue
o banco de dados "mpg" e seu dicionário:

```
library(tidyverse)
data(mpg)
help(mpg)
```

- Classifique o tipo de 
cada uma das variáveis no banco de dados.

- Construa um gráfico de dispersão entre
as variáveis "hwy" e "cyl".
Que tipo de associação linear você espera
entre estas variáveis?
O resultado é compatível com sua intuição?

- Utilizando o seguinte comando é possível
visualizar três variáveis simultaneamente:

```
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```
No eixo x observamos a cilindrada do motor,
no eixo y o número de milhas percorridas por
litro de combustível e a cor indica cada tipo de carro.
Interprete o gráfico obtido indicando como
o eixo x se relaciona com o eixo y.
Existe algum tipo de carro que é diferente das demais
em relação a esta relação?
Por que você acha que este é o caso?

3. Prove que para quaisquer valores de 
$X_1, X_2, \ldots, X_n$,
$$\frac{\sum_{i=1}^{n}{(X_i-\bar{X})^2}}{n} 
= \frac{\sum_{i=1}^{n}{X_i^2}}{n}-\bar{X}^2$$

4. Um baralho sem curingas é embaralhado.
Duas cartas são retiradas do topo do baralho.
Defina os eventos:
$A:$ a primeira carta é um rei,
$B:$ a segunda carta é um rei,
$C:$ a primeira carta é de espadas,
$D:$ a primeira carta é uma rainha.

- Para cada possível dupla de eventos,
determine se estes são mutuamente exclusivos.
Determine também se eles são independentes.

- Calcule $P(A \textbf{ e } B \textbf{ e } C)$.

- Calcule $P(A \textbf{ ou } B )$.

- Calcule $P((A \textbf{ ou } D) \textbf{ e } B)$.

5. Recorde-se que uma Binomial tem como parâmetros
n, o número de lançamento e $\theta$, a
probabilidade de cada lançamento ser cara.

- Como o valor esperado da binomial varia
de acordo com $n$ e $\theta$?

- Como a variância da binomial varia
de acordo com $n$ e $\theta$?
Qual o valor de $\theta$ que
maximiza a variância da binomial?

- Interprete os resultados acima.

6. Um sistema tem $10$ componentes
que falham independentemente com probabilidade $0.1$.

- Considere que o sistema tem os componentes em série,
isto é, ele falha se qualquer um dos componentes falhar.
Qual a probabilidade de o sistema falhar?

- Considere que o sistema tem os componentes em paralelos,
isto é, ele falha somente se todos os componentes falharem.
Qual a probabilidade de o sistema falhar.

- Considere que dois sub-sistemas são formados
a partir de $5$ componentes em série.
Se o sistema é composto pelos dois sub-sistemas em paralelo,
qual é a probabilidade de ele falhar?
